
<h1>Unverified Public Keys</h1>

<p>One or more of the BIP32 key-pairs did not match.  Below lists the public keys that did not match to any of the private keys submitted.  This means the addresses being generated by the software are not currently controlled by you, and you should immediately transfer the wallet via the Financial-&gt;Transfer Wallet menu.</p>

<div class="box">

	<table class="form_table">

	{section name=item loop=$keys}
	<tr>
		<td>Invalid Public Key #{$keys[item].num}</td>
		<td><textarea name="invalid_key" readonly>{$keys[item].public_key}</textarea></td>
	</tr>
	{/section}
	</table><br>

</div>
